import React from "react";
import weatherContext from "./weatherContext";

const WeatherState = (props) => {
  const state = {
    location: {
      name: "Jaipur",
      region: "Rajasthan",
      country: "India",
      lat: 26.92,
      lon: 75.82,
      tz_id: "Asia/Kolkata",
      localtime_epoch: 1685527360,
      localtime: "2023-05-31 15:32",
    },
    current: {
      last_updated_epoch: 1685527200,
      last_updated: "2023-05-31 15:30",
      temp_c: 31.0,
      temp_f: 87.8,
      is_day: 1,
      condition: {
        text: "Mist",
        icon: "//cdn.weatherapi.com/weather/64x64/day/143.png",
        code: 1030,
      },
      wind_mph: 10.5,
      wind_kph: 16.9,
      wind_degree: 310,
      wind_dir: "NW",
      pressure_mb: 1009.0,
      pressure_in: 29.8,
      precip_mm: 0.0,
      precip_in: 0.0,
      humidity: 52,
      cloud: 50,
      feelslike_c: 29.5,
      feelslike_f: 85.0,
      vis_km: 5.0,
      vis_miles: 3.0,
      uv: 9.0,
      gust_mph: 11.4,
      gust_kph: 18.4,
    },
    forecast: {
      forecastday: [
        {
          date: "2023-05-31",
          date_epoch: 1685491200,
          day: {
            maxtemp_c: 36.5,
            maxtemp_f: 97.7,
            mintemp_c: 24.3,
            mintemp_f: 75.7,
            avgtemp_c: 30.4,
            avgtemp_f: 86.7,
            maxwind_mph: 10.3,
            maxwind_kph: 16.6,
            totalprecip_mm: 0.3,
            totalprecip_in: 0.01,
            totalsnow_cm: 0.0,
            avgvis_km: 10.0,
            avgvis_miles: 6.0,
            avghumidity: 42.0,
            daily_will_it_rain: 1,
            daily_chance_of_rain: 83,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 0,
            condition: {
              text: "Patchy rain possible",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            uv: 7.0,
          },
          astro: {
            sunrise: "05:34 AM",
            sunset: "07:16 PM",
            moonrise: "03:34 PM",
            moonset: "02:44 AM",
            moon_phase: "Waxing Gibbous",
            moon_illumination: "81",
            is_moon_up: 0,
            is_sun_up: 0,
          },
          hour: [
            {
              time_epoch: 1685471400,
              time: "2023-05-31 00:00",
              temp_c: 26.6,
              temp_f: 79.9,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 9.6,
              wind_kph: 15.5,
              wind_degree: 309,
              wind_dir: "NW",
              pressure_mb: 1008.0,
              pressure_in: 29.77,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 52,
              cloud: 3,
              feelslike_c: 27.3,
              feelslike_f: 81.1,
              windchill_c: 26.6,
              windchill_f: 79.9,
              heatindex_c: 27.3,
              heatindex_f: 81.1,
              dewpoint_c: 15.9,
              dewpoint_f: 60.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 13.0,
              gust_kph: 20.9,
              uv: 1.0,
            },
            {
              time_epoch: 1685475000,
              time: "2023-05-31 01:00",
              temp_c: 25.9,
              temp_f: 78.6,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 8.5,
              wind_kph: 13.7,
              wind_degree: 321,
              wind_dir: "NW",
              pressure_mb: 1008.0,
              pressure_in: 29.75,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 57,
              cloud: 3,
              feelslike_c: 26.9,
              feelslike_f: 80.4,
              windchill_c: 25.9,
              windchill_f: 78.6,
              heatindex_c: 26.9,
              heatindex_f: 80.4,
              dewpoint_c: 16.7,
              dewpoint_f: 62.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 11.2,
              gust_kph: 18.0,
              uv: 1.0,
            },
            {
              time_epoch: 1685478600,
              time: "2023-05-31 02:00",
              temp_c: 25.4,
              temp_f: 77.7,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 5.8,
              wind_kph: 9.4,
              wind_degree: 322,
              wind_dir: "NW",
              pressure_mb: 1007.0,
              pressure_in: 29.75,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 60,
              cloud: 19,
              feelslike_c: 26.6,
              feelslike_f: 79.9,
              windchill_c: 25.4,
              windchill_f: 77.7,
              heatindex_c: 26.6,
              heatindex_f: 79.9,
              dewpoint_c: 17.1,
              dewpoint_f: 62.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 7.8,
              gust_kph: 12.6,
              uv: 1.0,
            },
            {
              time_epoch: 1685482200,
              time: "2023-05-31 03:00",
              temp_c: 25.0,
              temp_f: 77.0,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 5.6,
              wind_kph: 9.0,
              wind_degree: 296,
              wind_dir: "WNW",
              pressure_mb: 1008.0,
              pressure_in: 29.76,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 63,
              cloud: 19,
              feelslike_c: 26.3,
              feelslike_f: 79.3,
              windchill_c: 25.0,
              windchill_f: 77.0,
              heatindex_c: 26.3,
              heatindex_f: 79.3,
              dewpoint_c: 17.4,
              dewpoint_f: 63.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 7.6,
              gust_kph: 12.2,
              uv: 1.0,
            },
            {
              time_epoch: 1685485800,
              time: "2023-05-31 04:00",
              temp_c: 24.6,
              temp_f: 76.3,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 5.6,
              wind_kph: 9.0,
              wind_degree: 286,
              wind_dir: "WNW",
              pressure_mb: 1008.0,
              pressure_in: 29.76,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 64,
              cloud: 5,
              feelslike_c: 26.0,
              feelslike_f: 78.8,
              windchill_c: 24.6,
              windchill_f: 76.3,
              heatindex_c: 26.0,
              heatindex_f: 78.8,
              dewpoint_c: 17.4,
              dewpoint_f: 63.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 7.8,
              gust_kph: 12.6,
              uv: 1.0,
            },
            {
              time_epoch: 1685489400,
              time: "2023-05-31 05:00",
              temp_c: 24.3,
              temp_f: 75.7,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 4.9,
              wind_kph: 7.9,
              wind_degree: 296,
              wind_dir: "WNW",
              pressure_mb: 1008.0,
              pressure_in: 29.77,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 65,
              cloud: 3,
              feelslike_c: 25.8,
              feelslike_f: 78.4,
              windchill_c: 24.3,
              windchill_f: 75.7,
              heatindex_c: 25.8,
              heatindex_f: 78.4,
              dewpoint_c: 17.3,
              dewpoint_f: 63.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 7.2,
              gust_kph: 11.5,
              uv: 1.0,
            },
            {
              time_epoch: 1685493000,
              time: "2023-05-31 06:00",
              temp_c: 24.6,
              temp_f: 76.3,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 6.7,
              wind_kph: 10.8,
              wind_degree: 278,
              wind_dir: "W",
              pressure_mb: 1009.0,
              pressure_in: 29.79,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 62,
              cloud: 4,
              feelslike_c: 26.0,
              feelslike_f: 78.8,
              windchill_c: 24.6,
              windchill_f: 76.3,
              heatindex_c: 26.0,
              heatindex_f: 78.8,
              dewpoint_c: 17.0,
              dewpoint_f: 62.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 9.2,
              gust_kph: 14.8,
              uv: 6.0,
            },
            {
              time_epoch: 1685496600,
              time: "2023-05-31 07:00",
              temp_c: 25.8,
              temp_f: 78.4,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 9.2,
              wind_kph: 14.8,
              wind_degree: 273,
              wind_dir: "W",
              pressure_mb: 1009.0,
              pressure_in: 29.81,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 55,
              cloud: 4,
              feelslike_c: 26.7,
              feelslike_f: 80.1,
              windchill_c: 25.8,
              windchill_f: 78.4,
              heatindex_c: 26.7,
              heatindex_f: 80.1,
              dewpoint_c: 16.1,
              dewpoint_f: 61.0,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 11.0,
              gust_kph: 17.6,
              uv: 7.0,
            },
            {
              time_epoch: 1685500200,
              time: "2023-05-31 08:00",
              temp_c: 27.1,
              temp_f: 80.8,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 8.7,
              wind_kph: 14.0,
              wind_degree: 265,
              wind_dir: "W",
              pressure_mb: 1009.0,
              pressure_in: 29.81,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 49,
              cloud: 3,
              feelslike_c: 27.6,
              feelslike_f: 81.7,
              windchill_c: 27.1,
              windchill_f: 80.8,
              heatindex_c: 27.6,
              heatindex_f: 81.7,
              dewpoint_c: 15.5,
              dewpoint_f: 59.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 10.1,
              gust_kph: 16.2,
              uv: 7.0,
            },
            {
              time_epoch: 1685503800,
              time: "2023-05-31 09:00",
              temp_c: 28.5,
              temp_f: 83.3,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 9.6,
              wind_kph: 15.5,
              wind_degree: 257,
              wind_dir: "WSW",
              pressure_mb: 1010.0,
              pressure_in: 29.82,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 45,
              cloud: 4,
              feelslike_c: 28.8,
              feelslike_f: 83.8,
              windchill_c: 28.5,
              windchill_f: 83.3,
              heatindex_c: 28.8,
              heatindex_f: 83.8,
              dewpoint_c: 15.4,
              dewpoint_f: 59.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 11.2,
              gust_kph: 18.0,
              uv: 7.0,
            },
            {
              time_epoch: 1685507400,
              time: "2023-05-31 10:00",
              temp_c: 29.8,
              temp_f: 85.6,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 9.2,
              wind_kph: 14.8,
              wind_degree: 274,
              wind_dir: "W",
              pressure_mb: 1010.0,
              pressure_in: 29.81,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 41,
              cloud: 3,
              feelslike_c: 30.0,
              feelslike_f: 86.0,
              windchill_c: 29.8,
              windchill_f: 85.6,
              heatindex_c: 30.0,
              heatindex_f: 86.0,
              dewpoint_c: 15.1,
              dewpoint_f: 59.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 10.5,
              gust_kph: 16.9,
              uv: 7.0,
            },
            {
              time_epoch: 1685511000,
              time: "2023-05-31 11:00",
              temp_c: 33.8,
              temp_f: 92.8,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 7.8,
              wind_kph: 12.6,
              wind_degree: 276,
              wind_dir: "W",
              pressure_mb: 1009.0,
              pressure_in: 29.8,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 37,
              cloud: 6,
              feelslike_c: 35.2,
              feelslike_f: 95.4,
              windchill_c: 33.8,
              windchill_f: 92.8,
              heatindex_c: 35.2,
              heatindex_f: 95.4,
              dewpoint_c: 17.2,
              dewpoint_f: 63.0,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 8.9,
              gust_kph: 14.4,
              uv: 8.0,
            },
            {
              time_epoch: 1685514600,
              time: "2023-05-31 12:00",
              temp_c: 35.0,
              temp_f: 95.0,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 8.3,
              wind_kph: 13.3,
              wind_degree: 277,
              wind_dir: "W",
              pressure_mb: 1009.0,
              pressure_in: 29.78,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 34,
              cloud: 11,
              feelslike_c: 36.3,
              feelslike_f: 97.3,
              windchill_c: 35.0,
              windchill_f: 95.0,
              heatindex_c: 36.3,
              heatindex_f: 97.3,
              dewpoint_c: 16.7,
              dewpoint_f: 62.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 9.6,
              gust_kph: 15.5,
              uv: 9.0,
            },
            {
              time_epoch: 1685518200,
              time: "2023-05-31 13:00",
              temp_c: 36.1,
              temp_f: 97.0,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 8.7,
              wind_kph: 14.0,
              wind_degree: 274,
              wind_dir: "W",
              pressure_mb: 1008.0,
              pressure_in: 29.75,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 30,
              cloud: 7,
              feelslike_c: 37.1,
              feelslike_f: 98.8,
              windchill_c: 36.1,
              windchill_f: 97.0,
              heatindex_c: 37.1,
              heatindex_f: 98.8,
              dewpoint_c: 15.9,
              dewpoint_f: 60.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 10.1,
              gust_kph: 16.2,
              uv: 9.0,
            },
            {
              time_epoch: 1685521800,
              time: "2023-05-31 14:00",
              temp_c: 36.5,
              temp_f: 97.7,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 9.4,
              wind_kph: 15.1,
              wind_degree: 276,
              wind_dir: "W",
              pressure_mb: 1007.0,
              pressure_in: 29.73,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 27,
              cloud: 5,
              feelslike_c: 36.9,
              feelslike_f: 98.4,
              windchill_c: 36.5,
              windchill_f: 97.7,
              heatindex_c: 36.9,
              heatindex_f: 98.4,
              dewpoint_c: 14.7,
              dewpoint_f: 58.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 10.7,
              gust_kph: 17.3,
              uv: 9.0,
            },
            {
              time_epoch: 1685525400,
              time: "2023-05-31 15:00",
              temp_c: 36.5,
              temp_f: 97.7,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 9.8,
              wind_kph: 15.8,
              wind_degree: 281,
              wind_dir: "WNW",
              pressure_mb: 1006.0,
              pressure_in: 29.7,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 26,
              cloud: 4,
              feelslike_c: 36.5,
              feelslike_f: 97.7,
              windchill_c: 36.5,
              windchill_f: 97.7,
              heatindex_c: 36.5,
              heatindex_f: 97.7,
              dewpoint_c: 13.8,
              dewpoint_f: 56.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 11.4,
              gust_kph: 18.4,
              uv: 9.0,
            },
            {
              time_epoch: 1685529000,
              time: "2023-05-31 16:00",
              temp_c: 36.0,
              temp_f: 96.8,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 10.3,
              wind_kph: 16.6,
              wind_degree: 288,
              wind_dir: "WNW",
              pressure_mb: 1006.0,
              pressure_in: 29.69,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 25,
              cloud: 5,
              feelslike_c: 35.5,
              feelslike_f: 95.9,
              windchill_c: 36.0,
              windchill_f: 96.8,
              heatindex_c: 35.5,
              heatindex_f: 95.9,
              dewpoint_c: 12.8,
              dewpoint_f: 55.0,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 11.9,
              gust_kph: 19.1,
              uv: 9.0,
            },
            {
              time_epoch: 1685532600,
              time: "2023-05-31 17:00",
              temp_c: 35.4,
              temp_f: 95.7,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 10.3,
              wind_kph: 16.6,
              wind_degree: 288,
              wind_dir: "WNW",
              pressure_mb: 1006.0,
              pressure_in: 29.69,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 25,
              cloud: 5,
              feelslike_c: 34.7,
              feelslike_f: 94.5,
              windchill_c: 35.4,
              windchill_f: 95.7,
              heatindex_c: 34.7,
              heatindex_f: 94.5,
              dewpoint_c: 12.3,
              dewpoint_f: 54.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 11.9,
              gust_kph: 19.1,
              uv: 9.0,
            },
            {
              time_epoch: 1685536200,
              time: "2023-05-31 18:00",
              temp_c: 34.6,
              temp_f: 94.3,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 10.1,
              wind_kph: 16.2,
              wind_degree: 294,
              wind_dir: "WNW",
              pressure_mb: 1006.0,
              pressure_in: 29.7,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 26,
              cloud: 4,
              feelslike_c: 33.8,
              feelslike_f: 92.8,
              windchill_c: 34.6,
              windchill_f: 94.3,
              heatindex_c: 33.8,
              heatindex_f: 92.8,
              dewpoint_c: 12.1,
              dewpoint_f: 53.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 11.6,
              gust_kph: 18.7,
              uv: 8.0,
            },
            {
              time_epoch: 1685539800,
              time: "2023-05-31 19:00",
              temp_c: 33.4,
              temp_f: 92.1,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 7.6,
              wind_kph: 12.2,
              wind_degree: 317,
              wind_dir: "NW",
              pressure_mb: 1006.0,
              pressure_in: 29.71,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 29,
              cloud: 4,
              feelslike_c: 32.9,
              feelslike_f: 91.2,
              windchill_c: 33.4,
              windchill_f: 92.1,
              heatindex_c: 32.9,
              heatindex_f: 91.2,
              dewpoint_c: 13.0,
              dewpoint_f: 55.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 9.6,
              gust_kph: 15.5,
              uv: 1.0,
            },
            {
              time_epoch: 1685543400,
              time: "2023-05-31 20:00",
              temp_c: 31.6,
              temp_f: 88.9,
              is_day: 0,
              condition: {
                text: "Patchy rain possible",
                icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
                code: 1063,
              },
              wind_mph: 7.2,
              wind_kph: 11.5,
              wind_degree: 332,
              wind_dir: "NNW",
              pressure_mb: 1007.0,
              pressure_in: 29.73,
              precip_mm: 0.2,
              precip_in: 0.01,
              humidity: 31,
              cloud: 78,
              feelslike_c: 30.9,
              feelslike_f: 87.6,
              windchill_c: 31.6,
              windchill_f: 88.9,
              heatindex_c: 30.9,
              heatindex_f: 87.6,
              dewpoint_c: 12.6,
              dewpoint_f: 54.7,
              will_it_rain: 1,
              chance_of_rain: 83,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 11.4,
              gust_kph: 18.4,
              uv: 1.0,
            },
            {
              time_epoch: 1685547000,
              time: "2023-05-31 21:00",
              temp_c: 31.2,
              temp_f: 88.2,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 7.2,
              wind_kph: 11.5,
              wind_degree: 338,
              wind_dir: "NNW",
              pressure_mb: 1007.0,
              pressure_in: 29.75,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 32,
              cloud: 4,
              feelslike_c: 30.6,
              feelslike_f: 87.1,
              windchill_c: 31.2,
              windchill_f: 88.2,
              heatindex_c: 30.6,
              heatindex_f: 87.1,
              dewpoint_c: 12.7,
              dewpoint_f: 54.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 11.6,
              gust_kph: 18.7,
              uv: 1.0,
            },
            {
              time_epoch: 1685550600,
              time: "2023-05-31 22:00",
              temp_c: 30.7,
              temp_f: 87.3,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 6.5,
              wind_kph: 10.4,
              wind_degree: 348,
              wind_dir: "NNW",
              pressure_mb: 1008.0,
              pressure_in: 29.75,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 34,
              cloud: 5,
              feelslike_c: 30.2,
              feelslike_f: 86.4,
              windchill_c: 30.7,
              windchill_f: 87.3,
              heatindex_c: 30.2,
              heatindex_f: 86.4,
              dewpoint_c: 12.9,
              dewpoint_f: 55.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 10.7,
              gust_kph: 17.3,
              uv: 1.0,
            },
            {
              time_epoch: 1685554200,
              time: "2023-05-31 23:00",
              temp_c: 30.4,
              temp_f: 86.7,
              is_day: 0,
              condition: {
                text: "Patchy rain possible",
                icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
                code: 1063,
              },
              wind_mph: 6.5,
              wind_kph: 10.4,
              wind_degree: 7,
              wind_dir: "N",
              pressure_mb: 1007.0,
              pressure_in: 29.74,
              precip_mm: 0.1,
              precip_in: 0.0,
              humidity: 35,
              cloud: 73,
              feelslike_c: 29.9,
              feelslike_f: 85.8,
              windchill_c: 30.4,
              windchill_f: 86.7,
              heatindex_c: 29.9,
              heatindex_f: 85.8,
              dewpoint_c: 13.2,
              dewpoint_f: 55.8,
              will_it_rain: 0,
              chance_of_rain: 63,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 10.3,
              gust_kph: 16.6,
              uv: 1.0,
            },
          ],
        },
        {
          date: "2023-06-01",
          date_epoch: 1685577600,
          day: {
            maxtemp_c: 40.8,
            maxtemp_f: 105.4,
            mintemp_c: 24.9,
            mintemp_f: 76.8,
            avgtemp_c: 32.8,
            avgtemp_f: 91.0,
            maxwind_mph: 19.5,
            maxwind_kph: 31.3,
            totalprecip_mm: 1.0,
            totalprecip_in: 0.04,
            totalsnow_cm: 0.0,
            avgvis_km: 9.9,
            avgvis_miles: 6.0,
            avghumidity: 36.0,
            daily_will_it_rain: 1,
            daily_chance_of_rain: 82,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 0,
            condition: {
              text: "Patchy rain possible",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            uv: 7.0,
          },
          astro: {
            sunrise: "05:33 AM",
            sunset: "07:16 PM",
            moonrise: "04:32 PM",
            moonset: "03:16 AM",
            moon_phase: "Waxing Gibbous",
            moon_illumination: "88",
            is_moon_up: 0,
            is_sun_up: 0,
          },
          hour: [
            {
              time_epoch: 1685557800,
              time: "2023-06-01 00:00",
              temp_c: 29.5,
              temp_f: 85.1,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 6.5,
              wind_kph: 10.4,
              wind_degree: 14,
              wind_dir: "NNE",
              pressure_mb: 1007.0,
              pressure_in: 29.73,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 37,
              cloud: 5,
              feelslike_c: 29.2,
              feelslike_f: 84.6,
              windchill_c: 29.5,
              windchill_f: 85.1,
              heatindex_c: 29.2,
              heatindex_f: 84.6,
              dewpoint_c: 13.5,
              dewpoint_f: 56.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 10.7,
              gust_kph: 17.3,
              uv: 1.0,
            },
            {
              time_epoch: 1685561400,
              time: "2023-06-01 01:00",
              temp_c: 28.9,
              temp_f: 84.0,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 6.0,
              wind_kph: 9.7,
              wind_degree: 27,
              wind_dir: "NNE",
              pressure_mb: 1006.0,
              pressure_in: 29.72,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 40,
              cloud: 5,
              feelslike_c: 28.8,
              feelslike_f: 83.8,
              windchill_c: 28.9,
              windchill_f: 84.0,
              heatindex_c: 28.8,
              heatindex_f: 83.8,
              dewpoint_c: 14.0,
              dewpoint_f: 57.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 10.1,
              gust_kph: 16.2,
              uv: 1.0,
            },
            {
              time_epoch: 1685565000,
              time: "2023-06-01 02:00",
              temp_c: 28.3,
              temp_f: 82.9,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 5.8,
              wind_kph: 9.4,
              wind_degree: 47,
              wind_dir: "NE",
              pressure_mb: 1006.0,
              pressure_in: 29.7,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 42,
              cloud: 3,
              feelslike_c: 28.4,
              feelslike_f: 83.1,
              windchill_c: 28.3,
              windchill_f: 82.9,
              heatindex_c: 28.4,
              heatindex_f: 83.1,
              dewpoint_c: 14.3,
              dewpoint_f: 57.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 9.8,
              gust_kph: 15.8,
              uv: 1.0,
            },
            {
              time_epoch: 1685568600,
              time: "2023-06-01 03:00",
              temp_c: 27.8,
              temp_f: 82.0,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 5.1,
              wind_kph: 8.3,
              wind_degree: 67,
              wind_dir: "ENE",
              pressure_mb: 1006.0,
              pressure_in: 29.7,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 44,
              cloud: 3,
              feelslike_c: 28.0,
              feelslike_f: 82.4,
              windchill_c: 27.8,
              windchill_f: 82.0,
              heatindex_c: 28.0,
              heatindex_f: 82.4,
              dewpoint_c: 14.6,
              dewpoint_f: 58.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 8.9,
              gust_kph: 14.4,
              uv: 1.0,
            },
            {
              time_epoch: 1685572200,
              time: "2023-06-01 04:00",
              temp_c: 27.5,
              temp_f: 81.5,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 3.1,
              wind_kph: 5.0,
              wind_degree: 80,
              wind_dir: "E",
              pressure_mb: 1006.0,
              pressure_in: 29.7,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 46,
              cloud: 4,
              feelslike_c: 27.8,
              feelslike_f: 82.0,
              windchill_c: 27.5,
              windchill_f: 81.5,
              heatindex_c: 27.8,
              heatindex_f: 82.0,
              dewpoint_c: 14.9,
              dewpoint_f: 58.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 5.4,
              gust_kph: 8.6,
              uv: 1.0,
            },
            {
              time_epoch: 1685575800,
              time: "2023-06-01 05:00",
              temp_c: 27.1,
              temp_f: 80.8,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 1.1,
              wind_kph: 1.8,
              wind_degree: 76,
              wind_dir: "ENE",
              pressure_mb: 1007.0,
              pressure_in: 29.72,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 48,
              cloud: 5,
              feelslike_c: 27.6,
              feelslike_f: 81.7,
              windchill_c: 27.1,
              windchill_f: 80.8,
              heatindex_c: 27.6,
              heatindex_f: 81.7,
              dewpoint_c: 15.2,
              dewpoint_f: 59.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 2.0,
              gust_kph: 3.2,
              uv: 1.0,
            },
            {
              time_epoch: 1685579400,
              time: "2023-06-01 06:00",
              temp_c: 27.9,
              temp_f: 82.2,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 1.8,
              wind_kph: 2.9,
              wind_degree: 46,
              wind_dir: "NE",
              pressure_mb: 1007.0,
              pressure_in: 29.75,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 45,
              cloud: 7,
              feelslike_c: 28.1,
              feelslike_f: 82.6,
              windchill_c: 27.9,
              windchill_f: 82.2,
              heatindex_c: 28.1,
              heatindex_f: 82.6,
              dewpoint_c: 14.7,
              dewpoint_f: 58.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 2.7,
              gust_kph: 4.3,
              uv: 7.0,
            },
            {
              time_epoch: 1685583000,
              time: "2023-06-01 07:00",
              temp_c: 29.1,
              temp_f: 84.4,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 0.7,
              wind_kph: 1.1,
              wind_degree: 68,
              wind_dir: "ENE",
              pressure_mb: 1008.0,
              pressure_in: 29.76,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 40,
              cloud: 7,
              feelslike_c: 29.0,
              feelslike_f: 84.2,
              windchill_c: 29.1,
              windchill_f: 84.4,
              heatindex_c: 29.0,
              heatindex_f: 84.2,
              dewpoint_c: 14.0,
              dewpoint_f: 57.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 0.9,
              gust_kph: 1.4,
              uv: 7.0,
            },
            {
              time_epoch: 1685586600,
              time: "2023-06-01 08:00",
              temp_c: 30.6,
              temp_f: 87.1,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 2.9,
              wind_kph: 4.7,
              wind_degree: 216,
              wind_dir: "SW",
              pressure_mb: 1008.0,
              pressure_in: 29.77,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 35,
              cloud: 8,
              feelslike_c: 30.2,
              feelslike_f: 86.4,
              windchill_c: 30.6,
              windchill_f: 87.1,
              heatindex_c: 30.2,
              heatindex_f: 86.4,
              dewpoint_c: 13.6,
              dewpoint_f: 56.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 3.4,
              gust_kph: 5.4,
              uv: 8.0,
            },
            {
              time_epoch: 1685590200,
              time: "2023-06-01 09:00",
              temp_c: 31.9,
              temp_f: 89.4,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 5.4,
              wind_kph: 8.6,
              wind_degree: 230,
              wind_dir: "SW",
              pressure_mb: 1008.0,
              pressure_in: 29.76,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 33,
              cloud: 7,
              feelslike_c: 31.5,
              feelslike_f: 88.7,
              windchill_c: 31.9,
              windchill_f: 89.4,
              heatindex_c: 31.5,
              heatindex_f: 88.7,
              dewpoint_c: 13.6,
              dewpoint_f: 56.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 6.3,
              gust_kph: 10.1,
              uv: 8.0,
            },
            {
              time_epoch: 1685593800,
              time: "2023-06-01 10:00",
              temp_c: 33.0,
              temp_f: 91.4,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 5.4,
              wind_kph: 8.6,
              wind_degree: 229,
              wind_dir: "SW",
              pressure_mb: 1007.0,
              pressure_in: 29.74,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 32,
              cloud: 6,
              feelslike_c: 32.9,
              feelslike_f: 91.2,
              windchill_c: 33.0,
              windchill_f: 91.4,
              heatindex_c: 32.9,
              heatindex_f: 91.2,
              dewpoint_c: 14.3,
              dewpoint_f: 57.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 6.3,
              gust_kph: 10.1,
              uv: 8.0,
            },
            {
              time_epoch: 1685597400,
              time: "2023-06-01 11:00",
              temp_c: 37.1,
              temp_f: 98.8,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 5.8,
              wind_kph: 9.4,
              wind_degree: 223,
              wind_dir: "SW",
              pressure_mb: 1006.0,
              pressure_in: 29.72,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 30,
              cloud: 7,
              feelslike_c: 38.8,
              feelslike_f: 101.8,
              windchill_c: 37.1,
              windchill_f: 98.8,
              heatindex_c: 38.8,
              heatindex_f: 101.8,
              dewpoint_c: 16.9,
              dewpoint_f: 62.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 6.7,
              gust_kph: 10.8,
              uv: 9.0,
            },
            {
              time_epoch: 1685601000,
              time: "2023-06-01 12:00",
              temp_c: 38.4,
              temp_f: 101.1,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 7.6,
              wind_kph: 12.2,
              wind_degree: 217,
              wind_dir: "SW",
              pressure_mb: 1005.0,
              pressure_in: 29.69,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 28,
              cloud: 5,
              feelslike_c: 40.1,
              feelslike_f: 104.2,
              windchill_c: 38.4,
              windchill_f: 101.1,
              heatindex_c: 40.1,
              heatindex_f: 104.2,
              dewpoint_c: 16.5,
              dewpoint_f: 61.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 8.7,
              gust_kph: 14.0,
              uv: 9.0,
            },
            {
              time_epoch: 1685604600,
              time: "2023-06-01 13:00",
              temp_c: 38.3,
              temp_f: 100.9,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 8.7,
              wind_kph: 14.0,
              wind_degree: 227,
              wind_dir: "SW",
              pressure_mb: 1005.0,
              pressure_in: 29.66,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 25,
              cloud: 17,
              feelslike_c: 39.0,
              feelslike_f: 102.2,
              windchill_c: 38.3,
              windchill_f: 100.9,
              heatindex_c: 39.0,
              heatindex_f: 102.2,
              dewpoint_c: 14.8,
              dewpoint_f: 58.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 10.1,
              gust_kph: 16.2,
              uv: 9.0,
            },
            {
              time_epoch: 1685608200,
              time: "2023-06-01 14:00",
              temp_c: 38.6,
              temp_f: 101.5,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 7.8,
              wind_kph: 12.6,
              wind_degree: 241,
              wind_dir: "WSW",
              pressure_mb: 1004.0,
              pressure_in: 29.64,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 23,
              cloud: 20,
              feelslike_c: 38.8,
              feelslike_f: 101.8,
              windchill_c: 38.6,
              windchill_f: 101.5,
              heatindex_c: 38.8,
              heatindex_f: 101.8,
              dewpoint_c: 13.7,
              dewpoint_f: 56.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 8.9,
              gust_kph: 14.4,
              uv: 9.0,
            },
            {
              time_epoch: 1685611800,
              time: "2023-06-01 15:00",
              temp_c: 40.8,
              temp_f: 105.4,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 7.8,
              wind_kph: 12.6,
              wind_degree: 246,
              wind_dir: "WSW",
              pressure_mb: 1003.0,
              pressure_in: 29.62,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 21,
              cloud: 14,
              feelslike_c: 41.6,
              feelslike_f: 106.9,
              windchill_c: 40.8,
              windchill_f: 105.4,
              heatindex_c: 41.6,
              heatindex_f: 106.9,
              dewpoint_c: 14.4,
              dewpoint_f: 57.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 8.9,
              gust_kph: 14.4,
              uv: 10.0,
            },
            {
              time_epoch: 1685615400,
              time: "2023-06-01 16:00",
              temp_c: 39.2,
              temp_f: 102.6,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 12.1,
              wind_kph: 19.4,
              wind_degree: 250,
              wind_dir: "WSW",
              pressure_mb: 1002.0,
              pressure_in: 29.6,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 20,
              cloud: 11,
              feelslike_c: 38.8,
              feelslike_f: 101.8,
              windchill_c: 39.2,
              windchill_f: 102.6,
              heatindex_c: 38.8,
              heatindex_f: 101.8,
              dewpoint_c: 11.9,
              dewpoint_f: 53.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 13.9,
              gust_kph: 22.3,
              uv: 9.0,
            },
            {
              time_epoch: 1685619000,
              time: "2023-06-01 17:00",
              temp_c: 40.5,
              temp_f: 104.9,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 16.6,
              wind_kph: 26.6,
              wind_degree: 258,
              wind_dir: "WSW",
              pressure_mb: 1002.0,
              pressure_in: 29.58,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 20,
              cloud: 10,
              feelslike_c: 40.7,
              feelslike_f: 105.3,
              windchill_c: 40.5,
              windchill_f: 104.9,
              heatindex_c: 40.7,
              heatindex_f: 105.3,
              dewpoint_c: 13.1,
              dewpoint_f: 55.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 19.0,
              gust_kph: 30.6,
              uv: 10.0,
            },
            {
              time_epoch: 1685622600,
              time: "2023-06-01 18:00",
              temp_c: 38.5,
              temp_f: 101.3,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 17.0,
              wind_kph: 27.4,
              wind_degree: 256,
              wind_dir: "WSW",
              pressure_mb: 1002.0,
              pressure_in: 29.58,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 22,
              cloud: 11,
              feelslike_c: 38.4,
              feelslike_f: 101.1,
              windchill_c: 38.5,
              windchill_f: 101.3,
              heatindex_c: 38.4,
              heatindex_f: 101.1,
              dewpoint_c: 13.1,
              dewpoint_f: 55.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 19.5,
              gust_kph: 31.3,
              uv: 9.0,
            },
            {
              time_epoch: 1685626200,
              time: "2023-06-01 19:00",
              temp_c: 36.1,
              temp_f: 97.0,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 16.1,
              wind_kph: 25.9,
              wind_degree: 264,
              wind_dir: "W",
              pressure_mb: 1002.0,
              pressure_in: 29.6,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 26,
              cloud: 12,
              feelslike_c: 36.1,
              feelslike_f: 97.0,
              windchill_c: 36.1,
              windchill_f: 97.0,
              heatindex_c: 36.1,
              heatindex_f: 97.0,
              dewpoint_c: 13.8,
              dewpoint_f: 56.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 18.6,
              gust_kph: 29.9,
              uv: 1.0,
            },
            {
              time_epoch: 1685629800,
              time: "2023-06-01 20:00",
              temp_c: 34.0,
              temp_f: 93.2,
              is_day: 0,
              condition: {
                text: "Thundery outbreaks possible",
                icon: "//cdn.weatherapi.com/weather/64x64/night/200.png",
                code: 1087,
              },
              wind_mph: 15.2,
              wind_kph: 24.5,
              wind_degree: 280,
              wind_dir: "W",
              pressure_mb: 1003.0,
              pressure_in: 29.63,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 31,
              cloud: 27,
              feelslike_c: 34.1,
              feelslike_f: 93.4,
              windchill_c: 34.0,
              windchill_f: 93.2,
              heatindex_c: 34.1,
              heatindex_f: 93.4,
              dewpoint_c: 14.7,
              dewpoint_f: 58.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 9.0,
              vis_miles: 5.0,
              gust_mph: 22.1,
              gust_kph: 35.6,
              uv: 1.0,
            },
            {
              time_epoch: 1685633400,
              time: "2023-06-01 21:00",
              temp_c: 32.6,
              temp_f: 90.7,
              is_day: 0,
              condition: {
                text: "Thundery outbreaks possible",
                icon: "//cdn.weatherapi.com/weather/64x64/night/200.png",
                code: 1087,
              },
              wind_mph: 14.5,
              wind_kph: 23.4,
              wind_degree: 294,
              wind_dir: "WNW",
              pressure_mb: 1004.0,
              pressure_in: 29.63,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 38,
              cloud: 46,
              feelslike_c: 33.3,
              feelslike_f: 91.9,
              windchill_c: 32.6,
              windchill_f: 90.7,
              heatindex_c: 33.3,
              heatindex_f: 91.9,
              dewpoint_c: 16.3,
              dewpoint_f: 61.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 9.0,
              vis_miles: 5.0,
              gust_mph: 21.3,
              gust_kph: 34.2,
              uv: 1.0,
            },
            {
              time_epoch: 1685637000,
              time: "2023-06-01 22:00",
              temp_c: 26.1,
              temp_f: 79.0,
              is_day: 0,
              condition: {
                text: "Patchy rain possible",
                icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
                code: 1063,
              },
              wind_mph: 17.2,
              wind_kph: 27.7,
              wind_degree: 8,
              wind_dir: "N",
              pressure_mb: 1006.0,
              pressure_in: 29.71,
              precip_mm: 0.1,
              precip_in: 0.0,
              humidity: 62,
              cloud: 85,
              feelslike_c: 27.4,
              feelslike_f: 81.3,
              windchill_c: 26.1,
              windchill_f: 79.0,
              heatindex_c: 27.4,
              heatindex_f: 81.3,
              dewpoint_c: 18.1,
              dewpoint_f: 64.6,
              will_it_rain: 1,
              chance_of_rain: 71,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 22.6,
              gust_kph: 36.4,
              uv: 1.0,
            },
            {
              time_epoch: 1685640600,
              time: "2023-06-01 23:00",
              temp_c: 24.9,
              temp_f: 76.8,
              is_day: 0,
              condition: {
                text: "Patchy light rain with thunder",
                icon: "//cdn.weatherapi.com/weather/64x64/night/386.png",
                code: 1273,
              },
              wind_mph: 19.5,
              wind_kph: 31.3,
              wind_degree: 13,
              wind_dir: "NNE",
              pressure_mb: 1006.0,
              pressure_in: 29.71,
              precip_mm: 0.9,
              precip_in: 0.04,
              humidity: 65,
              cloud: 82,
              feelslike_c: 26.3,
              feelslike_f: 79.3,
              windchill_c: 24.9,
              windchill_f: 76.8,
              heatindex_c: 26.3,
              heatindex_f: 79.3,
              dewpoint_c: 18.0,
              dewpoint_f: 64.4,
              will_it_rain: 1,
              chance_of_rain: 82,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 25.3,
              gust_kph: 40.7,
              uv: 1.0,
            },
          ],
        },
      ],
    },
  };
  return (
    <weatherContext.Provider value={state}>
      {props.children}
    </weatherContext.Provider>
  );
};

export default WeatherState;
